// String translation map for non-JSON-key strings used across components
// This allows locale-based string selection: getString(locale, 'key')

const stringMap: Record<string, Record<string, string>> = {
  // Home page
  'home.morocco': { fr: 'Maroc', en: 'Morocco', es: 'Marruecos', nl: 'Marokko' },
  'home.discover': { fr: 'Découvrir', en: 'Discover', es: 'Descubrir', nl: 'Ontdekken' },
  'home.viewPricing': { fr: 'Voir les tarifs', en: 'View Pricing', es: 'Ver precios', nl: 'Bekijk prijzen' },
  'home.learnMore': { fr: 'En savoir plus', en: 'Learn More', es: 'Saber más', nl: 'Meer weten' },
  'home.activities': { fr: 'Nos activités', en: 'Our Activities', es: 'Nuestras Actividades', nl: 'Onze Activiteiten' },
  'home.wingkitesurf': { fr: 'Wingfoil, Kitesurf', en: 'Wingfoil, Kitesurf', es: 'Wingfoil, Kitesurf', nl: 'Wingfoil, Kitesurf' },
  'home.more': { fr: '& Plus encore', en: '& More', es: '& Más', nl: '& Meer' },
  'home.courses': { fr: 'Des cours adaptés à tous les niveaux dans le meilleur lagon du monde.', en: 'Courses adapted to all levels at the world\'s best lagoon.', es: 'Clases adaptadas a todos los niveles en la mejor laguna del mundo.', nl: 'Lessen aangepast aan alle niveaus in de beste lagune ter wereld.' },
  'home.rental': { fr: 'Location', en: 'Rental', es: 'Alquiler', nl: 'Verhuur' },
  'home.perfectSpot': { fr: 'Le spot parfait', en: 'The Perfect Spot', es: 'El spot perfecto', nl: 'De perfecte spot' },
  'home.dakhlaLagoon': { fr: 'Le Lagon de Dakhla', en: 'Dakhla Lagoon', es: 'Laguna de Dakhla', nl: 'Dakhla-lagune' },
  'home.flatWater': { fr: 'Eaux plates, vent constant, soleil 300 jours par an.', en: 'Flat water, constant wind, sunshine 300 days a year.', es: 'Agua plana, viento constante, sol 300 días al año.', nl: 'Vlak water, constante wind, zon 300 dagen per jaar.' },
  'home.years': { fr: 'ans', en: 'years', es: 'años', nl: 'jaren' },
  'home.students': { fr: 'Élèves formés', en: 'Students Trained', es: 'Estudiantes Formados', nl: 'Getrainde Studenten' },
  'home.experience': { fr: 'Ans d\'expérience', en: 'Years Experience', es: 'Años de Experiencia', nl: 'Jaren Ervaring' },
  'home.wind': { fr: 'Jours de vent/an', en: 'Wind Days/Year', es: 'Días de Viento/Año', nl: 'Windkeren/jaar' },
  'home.whyChooseUs': { fr: 'Pourquoi nous choisir', en: 'Why Choose Us', es: '¿Por qué elegirnos?', nl: 'Waarom kiezen voor ons?' },
  'home.excellence': { fr: 'L\'excellence au coeur de Dakhla', en: 'Excellence in the Heart of Dakhla', es: 'Excelencia en el corazón de Dakhla', nl: 'Excellentie in het hart van Dakhla' },
  'home.certifiedInstructors': { fr: 'Instructeurs Certifiés', en: 'Certified Instructors', es: 'Instructores Certificados', nl: 'Gecertificeerde Instructeurs' },
  'home.certifiedInstructorsDesc': { fr: 'Notre équipe passionnée avec 10+ ans d\'expérience vous accompagne dans votre progression en toute sécurité.', en: 'Our passionate team with 10+ years of experience guides your progress safely.', es: 'Nuestro equipo apasionado con 10+ años de experiencia te guía en tu progresión de forma segura.', nl: 'Ons gepassioneerde team met 10+ jaar ervaring begeleidt je voortgang veilig.' },
  'home.constantWind': { fr: 'Vent Constant', en: 'Constant Wind', es: 'Viento Constante', nl: 'Constante Wind' },
  'home.constantWindDesc': { fr: '300+ jours de vent par an avec des conditions idéales pour l\'apprentissage.', en: '300+ days of wind per year with ideal learning conditions.', es: '300+ días de viento al año con condiciones ideales para aprender.', nl: '300+ dagen wind per jaar met ideale leeromstandigheden.' },
  'home.perfectLagoon': { fr: 'Lagon Parfait', en: 'Perfect Lagoon', es: 'Laguna Perfecta', nl: 'Perfecte Lagune' },
  'home.perfectLagoonDesc': { fr: 'Eaux peu profondes et calmes, parfaites pour les débutants comme les experts.', en: 'Shallow, calm waters perfect for beginners and experts alike.', es: 'Aguas poco profundas y tranquilas, perfectas para principiantes y expertos.', nl: 'Ondiep en kalm water, perfect voor beginners en experts.' },
  'home.smallGroups': { fr: 'Petits Groupes', en: 'Small Groups', es: 'Grupos Pequeños', nl: 'Kleine Groepen' },
  'home.smallGroupsDesc': { fr: 'Attention personnalisée pour une progression optimale et un apprentissage efficace.', en: 'Personal attention for optimal progress and effective learning.', es: 'Atención personalizada para una progresión óptima y aprendizaje efectivo.', nl: 'Persoonlijke aandacht voor optimale voortgang en effectief leren.' },

  // About page
  'about.ourStory': { fr: 'Notre Histoire', en: 'Our Story', es: 'Nuestra Historia', nl: 'Ons Verhaal' },
  'about.passion': { fr: 'Passion, expertise et dévouement depuis plus de 10 ans', en: 'Passion, expertise and dedication for over 10 years', es: 'Pasión, experiencia y dedicación durante más de 10 años', nl: 'Passie, expertise en toewijding voor meer dan 10 jaar' },
  'about.ourMission': { fr: 'Notre Mission', en: 'Our Mission', es: 'Nuestra Misión', nl: 'Onze Missie' },
  'about.sharePassion': { fr: 'Partager notre passion pour le wingfoil et le kitesurf', en: 'Share our passion for wingfoil and kitesurf', es: 'Compartir nuestra pasión por el wingfoil y el kitesurf', nl: 'Deel onze passie voor wingfoil en kitesurf' },
  'about.ourValues': { fr: 'Nos Valeurs', en: 'Our Values', es: 'Nuestros Valores', nl: 'Onze Waarden' },
  'about.whatDefines': { fr: 'Ce qui nous définit', en: 'What defines us', es: 'Lo que nos define', nl: 'Wat ons definieert' },
  'about.safety': { fr: 'Sécurité', en: 'Safety', es: 'Seguridad', nl: 'Veiligheid' },
  'about.safetyDesc': { fr: 'Votre sécurité est notre priorité absolue. Équipements certifiés et protocoles stricts.', en: 'Your safety is our top priority. Certified equipment and strict protocols.', es: 'Tu seguridad es nuestra prioridad absoluta. Equipamiento certificado y protocolos estrictos.', nl: 'Jouw veiligheid is onze absolute prioriteit. Gecertificeerde uitrusting en strikte protocollen.' },
  'about.passion': { fr: 'Passion', en: 'Passion', es: 'Pasión', nl: 'Passie' },
  'about.passionDesc': { fr: 'Nous vivons et respirons les sports nautiques. Notre passion est contagieuse!', en: 'We live and breathe water sports. Our passion is contagious!', es: '¡Vivimos y respiramos los deportes acuáticos! ¡Nuestra pasión es contagiosa!', nl: 'We leven en ademen watersport. Onze passie is aanstekelijk!' },
  'about.progress': { fr: 'Progression', en: 'Progress', es: 'Progresión', nl: 'Voortgang' },
  'about.progressDesc': { fr: 'Méthodes pédagogiques éprouvées pour une progression rapide et durable.', en: 'Proven teaching methods for fast and lasting progress.', es: 'Métodos pedagógicos probados para una progresión rápida y duradera.', nl: 'Bewezen onderwijsmethoden voor snelle en duurzame voortgang.' },
  'about.respect': { fr: 'Respect', en: 'Respect', es: 'Respeto', nl: 'Respect' },
  'about.respectDesc': { fr: 'Respect de l\'environnement et des autres pratiquants sur le spot.', en: 'Respect for the environment and fellow riders on the spot.', es: 'Respeto por el medio ambiente y otros practicantes en el spot.', nl: 'Respect voor het milieu en medegebruikers op de spot.' },
  'about.ourTeam': { fr: 'Notre Équipe', en: 'Our Team', es: 'Nuestro Equipo', nl: 'Ons Team' },
  'about.certifiedInstructors': { fr: 'Des instructeurs passionnés et certifiés', en: 'Passionate and certified instructors', es: 'Instructores apasionados y certificados', nl: 'Gepassioneerde en gecertificeerde instructeurs' },
  'about.smallGroups': { fr: 'Petits groupes', en: 'Small groups', es: 'Grupos pequeños', nl: 'Kleine groepen' },
  'about.certified': { fr: 'Certifié IKO/VDWS', en: 'IKO/VDWS Certified', es: 'Certificado IKO/VDWS', nl: 'IKO/VDWS Gecertificeerd' },
  'about.ourSpot': { fr: 'Notre Spot', en: 'Our Spot', es: 'Nuestro Spot', nl: 'Onze Spot' },
  'about.dakhlaLagoon': { fr: 'Le lagon de Dakhla', en: 'The Dakhla Lagoon', es: 'La laguna de Dakhla', nl: 'De Dakhla-lagune' },
  'about.flatWater': { fr: 'Eau plate', en: 'Flat water', es: 'Agua plana', nl: 'Vlak water' },
  'about.flatWaterDesc': { fr: 'Lagon protégé, idéal pour débuter', en: 'Protected lagoon, ideal for beginners', es: 'Laguna protegida, ideal para principiantes', nl: 'Beschermde lagune, ideaal voor beginners' },
  'about.constantWind': { fr: 'Vent constant', en: 'Constant wind', es: 'Viento constante', nl: 'Constante wind' },
  'about.constantWindDesc': { fr: '300+ jours de vent par an', en: '300+ days of wind per year', es: '300+ días de viento al año', nl: '300+ windkeuren per jaar' },
  'about.sun': { fr: 'Soleil garanti', en: 'Guaranteed sun', es: 'Sol garantizado', nl: 'Gegarandeerde zon' },
  'about.sunDesc': { fr: 'Climat agréable toute l\'année', en: 'Pleasant climate year-round', es: 'Clima agradable todo el año', nl: 'Aangenaam klimaat het hele jaar door' },
  'about.readyJoinUs': { fr: 'Prêt à nous rejoindre?', en: 'Ready to join us?', es: '¿Listo para unirnos?', nl: 'Klaar om je bij ons aan te sluiten?' },
  'about.bookExperience': { fr: 'Réservez votre cours et vivez une expérience inoubliable à Dakhla.', en: 'Book your lesson and live an unforgettable experience in Dakhla.', es: 'Reserva tu clase y vive una experiencia inolvidable en Dakhla.', nl: 'Boek je les en beleef een onvergetelijke ervaring in Dakhla.' },
  'about.viewPricing': { fr: 'Voir les tarifs', en: 'View pricing', es: 'Ver precios', nl: 'Bekijk prijzen' },
  'about.contactUs': { fr: 'Nous contacter', en: 'Contact us', es: 'Contáctanos', nl: 'Neem contact op' },

  // Contact page
  'contact.contactUs': { fr: 'Contactez-nous', en: 'Contact Us', es: 'Contáctanos', nl: 'Neem contact op' },
  'contact.hereAnswer': { fr: 'Nous sommes là pour répondre à toutes vos questions', en: 'We are here to answer all your questions', es: 'Estamos aquí para responder a todas tus preguntas', nl: 'We zijn hier om al jouw vragen te beantwoorden' },
  'contact.sendMessage': { fr: 'Envoyez-nous un message', en: 'Send us a message', es: 'Envíanos un mensaje', nl: 'Stuur ons een bericht' },
  'contact.getBackSoon': { fr: 'Nous vous répondrons dans les plus brefs délais.', en: 'We will get back to you as soon as possible.', es: 'Te responderemos lo antes posible.', nl: 'We reageren zo snel mogelijk.' },
  'contact.info': { fr: 'Informations de contact', en: 'Contact Information', es: 'Información de contacto', nl: 'Contactgegevens' },
  'contact.address': { fr: 'Adresse', en: 'Address', es: 'Dirección', nl: 'Adres' },
  'contact.phone': { fr: 'Téléphone', en: 'Phone', es: 'Teléfono', nl: 'Telefoon' },
  'contact.hours': { fr: 'Horaires', en: 'Hours', es: 'Horarios', nl: 'Openingstijden' },
  'contact.everyDay': { fr: 'Tous les jours: 8h - 18h', en: 'Every day: 8am - 6pm', es: 'Todos los días: 8h - 18h', nl: 'Elke dag: 8u - 18u' },
  'contact.followUs': { fr: 'Suivez-nous', en: 'Follow Us', es: 'Síguenos', nl: 'Volg ons' },
  'contact.enjoyedExperience': { fr: 'Vous avez aimé votre expérience?', en: 'Did you enjoy your experience?', es: '¿Te gustó tu experiencia?', nl: 'Heb je je ervaring genoten?' },
  'contact.leaveReview': { fr: 'Laissez-nous un avis sur Google!', en: 'Leave us a review on Google!', es: '¡Déjanos una reseña en Google!', nl: 'Laat ons een recensie achter op Google!' },
  'contact.leaveReviewBtn': { fr: 'Laisser un avis', en: 'Leave a Review', es: 'Dejar una reseña', nl: 'Laat een recensie achter' },
  'contact.whatsappContact': { fr: 'Contactez-nous sur WhatsApp', en: 'Contact us on WhatsApp', es: 'Contáctanos en WhatsApp', nl: 'Neem contact met ons op via WhatsApp' },
  'contact.quickResponse': { fr: 'Réponse rapide garantie', en: 'Quick response guaranteed', es: 'Respuesta rápida garantizada', nl: 'Snelle respons gegarandeerd' },
  'contact.whereFind': { fr: 'Où nous trouver', en: 'Where to find us', es: 'Dónde encontrarnos', nl: 'Waar je ons vindt' },
  'contact.located': { fr: 'Situé sur le magnifique lagon de Dakhla, Maroc', en: 'Located on the beautiful Dakhla lagoon, Morocco', es: 'Ubicado en la hermosa laguna de Dakhla, Marruecos', nl: 'Gelegen aan de prachtige Dakhla-lagune, Marokko' },
  'contact.openMaps': { fr: 'Ouvrir dans Google Maps', en: 'Open in Google Maps', es: 'Abrir en Google Maps', nl: 'Openen in Google Maps' },
  'contact.byPlane': { fr: 'Par avion', en: 'By plane', es: 'Por avión', nl: 'Per vliegtuig' },
  'contact.airportTransfer': { fr: 'Aéroport de Dakhla (VIL) - 15 min en voiture', en: 'Dakhla Airport (VIL) - 15 min by car', es: 'Aeropuerto de Dakhla (VIL) - 15 minutos en coche', nl: 'Luchthaven Dakhla (VIL) - 15 minuten met de auto' },
  'contact.byCar': { fr: 'Par la route', en: 'By car', es: 'Por carretera', nl: 'Per auto' },
  'contact.fromCenter': { fr: 'Depuis le centre-ville de Dakhla - 20 min', en: 'From Dakhla city center - 20 min', es: 'Desde el centro de la ciudad de Dakhla - 20 minutos', nl: 'Vanuit het stadscentrum van Dakhla - 20 minuten' },
  'contact.transfer': { fr: 'Transfert', en: 'Transfer', es: 'Transferencia', nl: 'Transfer' },
  'contact.transferAvailable': { fr: 'Service de transfert disponible sur demande', en: 'Transfer service available on request', es: 'Servicio de transferencia disponible bajo solicitud', nl: 'Transferservice beschikbaar op aanvraag' },
  'contact.faq': { fr: 'Questions fréquentes', en: 'Frequently Asked Questions', es: 'Preguntas frecuentes', nl: 'Veelgestelde vragen' },
  'contact.offerBeginners': { fr: 'Proposez-vous des cours pour débutants?', en: 'Do you offer courses for beginners?', es: '¿Ofrecen cursos para principiantes?', nl: 'Bieden jullie lessen voor beginners?' },
  'contact.yesBeginners': { fr: 'Oui! Nous avons des cours spécialement conçus pour les débutants avec du matériel adapté.', en: 'Yes! We have courses specifically designed for beginners with adapted equipment.', es: '¡Sí! Tenemos cursos especialmente diseñados para principiantes con equipamiento adaptado.', nl: 'Ja! We hebben lessen speciaal ontworpen voor beginners met aangepaste uitrusting.' },
  'contact.provideEquipment': { fr: 'Fournissez-vous l\'équipement?', en: 'Do you provide equipment?', es: '¿Proporcionan equipamiento?', nl: 'Leveren jullie uitrusting?' },
  'contact.allEquipmentIncluded': { fr: 'Tout l\'équipement est inclus dans nos cours: wing, planche, combinaison et gilet.', en: 'All equipment is included in our courses: wing, board, wetsuit and vest.', es: 'Todo el equipamiento está incluido en nuestros cursos: ala, tabla, traje de neopreno y chaleco.', nl: 'Alle uitrusting is inbegrepen in onze lessen: vleugel, board, wetsuit en vest.' },
  'contact.bestSeason': { fr: 'Quelle est la meilleure saison?', en: 'What is the best season?', es: '¿Cuál es la mejor temporada?', nl: 'Wat is het beste seizoen?' },
  'contact.dakhlaManyConditions': { fr: 'Dakhla offre d\'excellentes conditions toute l\'année avec 300+ jours de vent.', en: 'Dakhla offers excellent conditions year-round with 300+ days of wind.', es: 'Dakhla ofrece excelentes condiciones todo el año con 300+ días de viento.', nl: 'Dakhla biedt het hele jaar ideale omstandigheden met 300+ windkeuren.' },
  'contact.howBook': { fr: 'Comment réserver?', en: 'How to book?', es: '¿Cómo reservar?', nl: 'Hoe reserveer ik?' },
  'contact.contactByPhone': { fr: 'Contactez-nous par téléphone, WhatsApp, email ou via ce formulaire.', en: 'Contact us by phone, WhatsApp, email or through this form.', es: 'Contáctanos por teléfono, WhatsApp, correo electrónico o a través de este formulario.', nl: 'Neem contact met ons op per telefoon, WhatsApp, e-mail of via dit formulier.' },
}

export type Locale = 'fr' | 'en' | 'es' | 'nl'

export function getString(locale: Locale, key: string): string {
  return stringMap[key]?.[locale] ?? stringMap[key]?.['en'] ?? key
}
